server:
  port: 8009

spring:
  main:
    web-application-type: reactive
#  data:
#     redis:
#      password: redis
  cache:
    cache-names: "organization, user"
  application:
      name: im-gateway

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] tenantId=%X{tenantId:-}"

multitenancy:
    http:
        header-name: X-TenantId
    security:
        issuer-base-uri: http://im-keycloak:8080/realms/

f2:
  tenant:
    issuer-base-uri: http://im-keycloak:8080

connect:
  fs:
    url: http://fs:8090
  im:
    keycloak:
        url: http://im-keycloak:8080
        realm: master
        clientId: im-root-client
        clientSecret: secret
    organization:
      insee:
        token: ${INSEE_TOKEN}
        sireneApi: https://api.insee.fr/entreprises/sirene/V3
    user:
      defaultRoleIdentifiers: ""
    smtp:
        host: connect-fake-smtp,
        port: 1025,
        from: noreply@komune.io,
        ssl: false,
        starttls: false,
        auth: false

---
spring:
  config:
    activate:
      on-profile: test

f2:
  tenant:
    issuer-base-uri: http://localhost:8080

connect:
  im:
    keycloak:
      url: http://localhost:8080
      realm: master
      clientId: im-root-client
      clientSecret: secret
